server:
  port: 8081

spring:
  # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dummy?currentSchema=public
    username: postgres
    password: root123
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
